"""Render docs/data_dictionary.md from the semantic JSON files.

Usage: uv run python scripts/write_data_dictionary.py
"""

from __future__ import annotations

from pathlib import Path

from loom.config import get_settings
from loom.semantic.models import DatasetSemantics


def render(sem: DatasetSemantics) -> str:
    lines = [f"## Dataset `{sem.dataset}`", ""]
    for t in sem.tables:
        span = (
            f" Time range: {t.time_min} to {t.time_max} (`{t.time_column}`)."
            if t.time_column
            else ""
        )
        lines += [
            f"### Table `{t.name}`",
            "",
            f"{t.description}{span}",
            "",
            f"- Grain: {t.grain}",
            f"- Rows: {t.row_count:,}",
            "",
            "| Column | Type | Description | Unit | Null % | Distinct |",
            "|---|---|---|---|---:|---:|",
        ]
        for c in t.columns:
            lines.append(
                f"| `{c.name}` | {c.dtype} | {c.description} | {c.unit or ''} | "
                f"{c.null_fraction * 100:.1f} | {c.distinct_count or ''} |"
            )
        lines.append("")
    lines += [
        "### Allowed joins",
        "",
        "| Left | Right | On | Kind | Note |",
        "|---|---|---|---|---|",
    ]
    for j in sem.joins:
        lines.append(f"| `{j.left_table}` | `{j.right_table}` | `{j.on}` | {j.kind} | {j.note} |")
    lines += [
        "",
        "### Metrics",
        "",
        "| Metric | Definition | SQL | Unit | Grain | Caveats |",
        "|---|---|---|---|---|---|",
    ]
    for m in sem.metrics:
        lines.append(
            f"| `{m.name}` | {m.definition} | `{m.sql_expression}` | {m.unit} | {m.grain} | {m.caveats} |"
        )
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    settings = get_settings()
    parts = [
        "# Data dictionary",
        "",
        "Generated by `scripts/write_data_dictionary.py` from `data/semantic/*.json`.",
        "",
    ]
    for path in sorted(Path(settings.semantic_dir).glob("*.json")):
        parts.append(render(DatasetSemantics.model_validate_json(path.read_text())))
    out = Path("docs/data_dictionary.md")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(parts))
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
